### ISSUE TITLE
Test fails with gcc

### ISSUE THREAD

**Issue by scemama** [v1j4y/qmckl_dgemm#2]
I started to fix it in the TREX branch, but it is still failing...

**Comment by v1j4y** [comment]
OK will work on it tomorrow.

PS: Do tests pass for you with intel compilers ?

**Comment by scemama** [comment]
Yes, it works with Intel. The problem is only in the GCC test

**Comment by v1j4y** [comment]
Fixed in [521e1d8](https://github.com/v1j4y/qmckl_dgemm/commit/521e1d834594a675bf71947f75f0d2513a3cfb10)

Please confirm and close.

**Comment by scemama** [comment]
Yes, intel is OK.
